# Generated by Django 4.2.5 on 2023-09-17 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='country',
            field=models.CharField(blank=True, default=None, max_length=30, null=True, verbose_name='Страна'),
        ),
        migrations.AddField(
            model_name='game',
            name='draft',
            field=models.BooleanField(default=False, verbose_name='Черновик'),
        ),
        migrations.AddField(
            model_name='game',
            name='year',
            field=models.PositiveSmallIntegerField(default=2019, verbose_name='Дата выхода'),
        ),
    ]
